Repository WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a, pull requests merged in 2023-12, with the labels that each got.

#10 Feature/ingredient table
  bun.lockb
  package.json
  packages/backend/forge/.eslintrc
  packages/backend/forge/.gitignore
  packages/backend/forge/README.md
  packages/backend/forge/package.json
  packages/backend/forge/src/index.ts
  packages/backend/forge/tsconfig.json
  packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
Labels: Sylvain !, Changes done

#11 Feature/database data
  packages/backend/forge/src/database-data.ts
  packages/backend/migrations/src/migrations/20231201111652-edit-glass-table.ts
Labels: Sylvain !

#6 front end done
  bun.lockb
  packages/frontend/web/package.json
  packages/frontend/web/public/form-cocktail/arrow-yellow.png
  packages/frontend/web/public/form-cocktail/bubble/bubble-1.png
  packages/frontend/web/public/form-cocktail/bubble/bubble-2.png
  packages/frontend/web/public/form-cocktail/bubble/bubble-3.png
  packages/frontend/web/public/form-cocktail/bubble/bubble-4.png
  packages/frontend/web/public/form-cocktail/bubble/bubble-5.png
  packages/frontend/web/public/form-cocktail/bubble/bubble-6.png
  packages/frontend/web/public/form-cocktail/fire-level.png
  packages/frontend/web/public/polygon-black.png
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/web/src/components/form-cocktail/NamePart.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/components/icons/ShakerIcon.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/types/src/cocktail-form.ts
  packages/types/src/index.ts
Labels: Sylvain !

#7 cocktails details page, only front part
  bun.lockb
  packages/frontend/web/package.json
  packages/frontend/web/public/bg-details.png
  packages/frontend/web/public/cocktail-placeholder.png
  packages/frontend/web/public/comment.png
  packages/frontend/web/public/feeding-bottle.svg
  packages/frontend/web/public/shaker.svg
  packages/frontend/web/public/star-yellow.png
  packages/frontend/web/public/star.png
  packages/frontend/web/public/vite.svg
  packages/frontend/web/src/components/CocktailCard.tsx
  packages/frontend/web/src/components/CocktailComments.tsx
  packages/frontend/web/src/components/CocktailForm.tsx
  packages/frontend/web/src/components/Comment.tsx
  packages/frontend/web/src/components/Star.tsx
  packages/frontend/web/src/components/StarRating.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/types/src/cocktail-detail.ts
  packages/types/src/index.ts
Labels: Sylvain !

#12 Feature/auth backend
  bun.lockb
  packages/backend/api/package.json
  packages/backend/api/src/auth.ts
  packages/backend/api/src/index.ts
  packages/backend/api/src/middlewares/validate-login.ts
  packages/backend/api/src/middlewares/validate-register.ts
  packages/backend/api/src/router.ts
  packages/backend/migrations/src/migrations/20231205142035-edit-user.ts
  packages/types/src/auth-login.ts
  packages/types/src/auth-register.ts
  packages/types/src/database.ts
  packages/types/src/index.ts
Labels: Sylvain !

#13 feat: generation of an alcohols list based on the strength selected b…
  packages/backend/api/src/router.ts
  packages/backend/api/src/services/alcohol-service.ts
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/types/src/cocktail-form.ts
Labels: Sylvain !, Conflicts resolved

#16 fix: auth-backend
  packages/backend/api/src/auth.ts
  packages/backend/api/src/index.ts
  packages/backend/api/src/middlewares/validate-login.ts
  packages/backend/api/src/middlewares/validate-register.ts
  packages/backend/migrations/src/migrations/20231206155749-edit-user-2.ts
  packages/types/src/auth-register.ts
  packages/types/src/database.ts
Labels: Sylvain !

#15 Feature/cocktail detail upload
  .env.sample
  .eslintrc.cjs
  bun.lockb
  packages/backend/api/package.json
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/router.ts
  packages/backend/migrations/src/migrations/20231205140742-image-nullable.ts
  packages/backend/migrations/src/migrations/20231205145821-add-anecdote-field.ts
  packages/backend/shared/src/lib/database.ts
  packages/frontend/web/src/components/CocktailForm.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailCard.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
  packages/frontend/web/src/components/cocktail-detail/Comment.tsx
  packages/frontend/web/src/components/cocktail-detail/Star.tsx
  packages/frontend/web/src/components/cocktail-detail/StarRating.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/router.tsx
  packages/types/src/cocktail-detail.ts
  packages/types/src/database.ts
Labels: Sylvain !

#14 feat: by an ingredient, generate ingredients than often come with it
  packages/backend/api/src/ingredient.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/hooks/use-fetch.ts
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/types/src/cocktail-form.ts
Labels: Sylvain !

#19 feat: a wonderful and responsive homepage
  packages/frontend/web/public/home/home-1.png
  packages/frontend/web/public/home/home-2.png
  packages/frontend/web/public/home/home-3.png
  packages/frontend/web/public/home/home-4.png
  packages/frontend/web/public/home/home-5.png
  packages/frontend/web/public/home/home-6.png
  packages/frontend/web/src/components/home/CocktailsPart.tsx
  packages/frontend/web/src/components/home/CommunityPart.tsx
  packages/frontend/web/src/components/home/FavoritesPart.tsx
  packages/frontend/web/src/components/home/ProfilePart.tsx
  packages/frontend/web/src/components/home/ShakeItPart.tsx
  packages/frontend/web/src/components/home/VirginPart.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !

#24 Feature/legal notice
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/src/pages/LegalModal.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !

#21 feat: back-end of glassPart
  packages/backend/api/src/glass.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/types/src/cocktail-form.ts
Labels: Sylvain !

#20 Feature/profil page
  packages/backend/api/src/router.ts
  packages/backend/api/src/user.ts
  packages/frontend/web/public/comment-1.png
  packages/frontend/web/public/placeholder-cocktail-virgin.webp
  packages/frontend/web/public/placeholder-cocktail.webp
  packages/frontend/web/public/profile-page/avatar.webp
  packages/frontend/web/public/profile-page/bg-profil-page.webp
  packages/frontend/web/public/profile-page/bubble.png
  packages/frontend/web/public/profile-page/miss-hold-it.webp
  packages/frontend/web/public/profile-page/profile-header.png
  packages/frontend/web/src/components/profile-page/Card.tsx
  packages/frontend/web/src/components/profile-page/Comments.tsx
  packages/frontend/web/src/components/profile-page/CommentsSection.tsx
  packages/frontend/web/src/components/profile-page/Header.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/ProfilePage.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/types/src/index.ts
  packages/types/src/profile.ts
Labels: Sylvain !

#26 Hotfix/style home page
  packages/frontend/web/public/dot/dot-1.svg
  packages/frontend/web/public/dot/dot-2.svg
  packages/frontend/web/public/dot/dot-3.svg
  packages/frontend/web/public/dot/dot-4.svg
  packages/frontend/web/public/dot/dot-5.svg
  packages/frontend/web/public/dot/dot-6.svg
  packages/frontend/web/public/home/home-1.png
  packages/frontend/web/public/home/home-2.png
  packages/frontend/web/public/home/home-3.png
  packages/frontend/web/public/home/home-4.png
  packages/frontend/web/public/home/home-5.png
  packages/frontend/web/public/home/home-6.png
  packages/frontend/web/src/components/home/CocktailsPart.tsx
  packages/frontend/web/src/components/home/CommunityPart.tsx
  packages/frontend/web/src/components/home/FavoritesPart.tsx
  packages/frontend/web/src/components/home/ProfilePart.tsx
  packages/frontend/web/src/components/home/ShakeItPart.tsx
  packages/frontend/web/src/components/home/VirginPart.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !

#22 Feature/cocktail details ingredients
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/comment.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/public/comment.jpg
  packages/frontend/web/src/components/cocktail-detail/AddComment.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailCard.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
  packages/frontend/web/src/components/cocktail-detail/Comment.tsx
  packages/frontend/web/src/components/cocktail-detail/Star.tsx
  packages/frontend/web/src/components/cocktail-detail/StarRating.tsx
  packages/frontend/web/src/hooks/use-outside-click.ts
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/router.tsx
  packages/types/src/cocktail-detail.ts
  packages/types/src/index.ts
Labels: Sylvain !

#28 feat: front of community page
  packages/backend/api/src/user.ts
  packages/backend/forge/src/database-data.ts
  packages/backend/migrations/src/migrations/20231219182930-user-update.ts
  packages/frontend/web/public/avatar/avatar-1.webp
  packages/frontend/web/public/avatar/avatar-10.webp
  packages/frontend/web/public/avatar/avatar-11.webp
  packages/frontend/web/public/avatar/avatar-12.webp
  packages/frontend/web/public/avatar/avatar-13.webp
  packages/frontend/web/public/avatar/avatar-14.webp
  packages/frontend/web/public/avatar/avatar-15.webp
  packages/frontend/web/public/avatar/avatar-16.webp
  packages/frontend/web/public/avatar/avatar-17.webp
  packages/frontend/web/public/avatar/avatar-18.webp
  packages/frontend/web/public/avatar/avatar-19.webp
  packages/frontend/web/public/avatar/avatar-2.webp
  packages/frontend/web/public/avatar/avatar-20.webp
  packages/frontend/web/public/avatar/avatar-21.webp
  packages/frontend/web/public/avatar/avatar-22.webp
  packages/frontend/web/public/avatar/avatar-3.webp
  packages/frontend/web/public/avatar/avatar-4.webp
  packages/frontend/web/public/avatar/avatar-5.webp
  packages/frontend/web/public/avatar/avatar-6.webp
  packages/frontend/web/public/avatar/avatar-7.webp
  packages/frontend/web/public/avatar/avatar-8.webp
  packages/frontend/web/public/avatar/avatar-9.webp
  packages/frontend/web/public/community/bg-all-profile.webp
  packages/frontend/web/public/community/header-community.png
  packages/frontend/web/src/pages/Community.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !
