Repository WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a, pull requests merged in 2024-02, with the labels that each got.

#69 Feature/devteam
  packages/frontend/web/public/avatar/avatar-23.webp
  packages/frontend/web/public/cedpic.jpeg
  packages/frontend/web/public/icon-github-planet.svg
  packages/frontend/web/public/icon-linkedin-1.svg
  packages/frontend/web/public/icon-linkedin.svg
  packages/frontend/web/public/jaapic.jpg
  packages/frontend/web/public/justinepic.jpg
  packages/frontend/web/public/noemiepic.jpg
  packages/frontend/web/public/yummycorn.svg
  packages/frontend/web/src/components/ShowTeam.tsx
  packages/frontend/web/src/router.tsx
Labels: Sylvain !, Changes done

#73 hotfix : comma
  packages/backend/forge/src/database-data.ts
Labels: Sylvain !

#51 Feature/shaker post
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/glass.ts
  packages/backend/api/src/ingredient.ts
  packages/backend/api/src/middlewares/validate-cocktail-add.ts
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/types/src/cocktail-form.ts
  packages/types/src/database.ts
Labels: Sylvain !

#59 Feature/navbar login logout
  packages/backend/api/src/auth.ts
  packages/frontend/web/src/components/Navbar.tsx
Labels: Sylvain !

#76 edit db structure
  packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
Labels: Sylvain !

#78 Feature/fix security on update profile
  packages/backend/api/src/user.ts
Labels: Sylvain !

#79 feat: error-404
  packages/frontend/web/public/blurring-glass.jpg
  packages/frontend/web/src/components/NotFound.tsx
  packages/frontend/web/src/router.tsx
Labels: Sylvain !

#32 feat : shakerPart in react native
  .tools/tsconfig.json
  bun.lockb
  packages/backend/api/src/services/topping-service.ts
  packages/backend/api/tsconfig.json
  packages/backend/forge/tsconfig.json
  packages/backend/migrations/tsconfig.json
  packages/backend/shared/tsconfig.json
  packages/frontend/admin/tsconfig.json
  packages/frontend/mobile/colors.ts
  packages/frontend/mobile/package.json
  packages/frontend/mobile/public/form-cocktail/arrow-yellow.png
  packages/frontend/mobile/public/form-cocktail/bubble/bubble-1.png
  packages/frontend/mobile/public/form-cocktail/bubble/bubble-2.png
  packages/frontend/mobile/public/form-cocktail/bubble/bubble-3.png
  packages/frontend/mobile/public/form-cocktail/bubble/bubble-4.png
  packages/frontend/mobile/public/form-cocktail/bubble/bubble-5.png
  packages/frontend/mobile/public/form-cocktail/bubble/bubble-6.png
  packages/frontend/mobile/public/form-cocktail/fire-level.png
  packages/frontend/mobile/src/App.tsx
  packages/frontend/mobile/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/mobile/src/components/form-cocktail/GlassPart.tsx
  packages/frontend/mobile/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/mobile/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/mobile/src/components/form-cocktail/NamePart.tsx
  packages/frontend/mobile/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/mobile/src/components/form-cocktail/icons/ShakerIcon.tsx
  packages/frontend/mobile/src/pages/AddCocktailScreen.tsx
  packages/frontend/mobile/tsconfig.json
  packages/frontend/shared/src/hooks/use-fetch.ts
  packages/frontend/shared/tsconfig.json
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/tsconfig.json
  packages/types/src/cocktail-form.ts
  packages/types/tsconfig.json
  tsconfig.json
Labels: Sylvain !, Native

#80 feat: date-legal-modal
  packages/frontend/web/src/components/Navbar.tsx
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/src/pages/LegalModal.tsx
Labels: Sylvain !

#83 feature loading on login
  .tools/tsconfig.json
  bun.lockb
  packages/backend/api/tsconfig.json
  packages/backend/forge/tsconfig.json
  packages/backend/migrations/tsconfig.json
  packages/backend/shared/tsconfig.json
  packages/frontend/admin/tsconfig.json
  packages/frontend/mobile/tsconfig.json
  packages/frontend/shared/tsconfig.json
  packages/frontend/web/package.json
  packages/frontend/web/src/pages/Loading.tsx
  packages/frontend/web/src/pages/Login.tsx
  packages/frontend/web/tailwind.config.js
  packages/frontend/web/tsconfig.json
  packages/types/tsconfig.json
  tsconfig.json
Labels: Sylvain !, Conflicts resolved

#84 Feature/cocktail rating
  packages/backend/api/src/auth.ts
  packages/backend/api/src/rating.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/src/components/cocktail-detail/AddComment.tsx
  packages/frontend/web/src/contexts/AuthContext.tsx
  packages/types/src/index.ts
Labels: Sylvain !, Conflicts resolved

#86 Feature/migrations update
  packages/backend/forge/src/database-data.ts
  packages/backend/migrations/src/migrations/20240206085522-topping-flavour.ts
Labels: Sylvain !, Changes done, Réponse

#82 feature: favicon
  .tools/tsconfig.json
  bun.lockb
  packages/backend/api/tsconfig.json
  packages/backend/forge/tsconfig.json
  packages/backend/migrations/tsconfig.json
  packages/backend/shared/tsconfig.json
  packages/frontend/admin/tsconfig.json
  packages/frontend/mobile/tsconfig.json
  packages/frontend/shared/tsconfig.json
  packages/frontend/web/index.html
  packages/frontend/web/public/yummycorn-favicon.png
  packages/frontend/web/tsconfig.json
  packages/types/tsconfig.json
  tsconfig.json
Labels: Sylvain !

#89 fixing docker compose
  deployment/docker-compose.dev.yml
Labels: Sylvain !

#88 not same ingredients twice
  packages/backend/api/src/ingredient.ts
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
Labels: Sylvain !

#90 Feature/alcohol router
  packages/backend/api/src/alcohol.ts
  packages/backend/api/src/router.ts
  packages/frontend/mobile/src/pages/AddCocktailScreen.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
Labels: Sylvain !

#52 Feature/favorite
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/favorite.ts
  packages/backend/api/src/middlewares/block-not-login.ts
  packages/backend/api/src/middlewares/check-auth-state.ts
  packages/backend/api/src/router.ts
  packages/backend/api/src/user.ts
  packages/backend/forge/src/database-data.ts
  packages/frontend/web/public/dot-favorites.png
  packages/frontend/web/public/favorites-bg.webp
  packages/frontend/web/public/heart.png
  packages/frontend/web/src/components/FavoriteHeart.tsx
  packages/frontend/web/src/components/Navbar.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
  packages/frontend/web/src/components/cocktail-detail/SimilarCocktail.tsx
  packages/frontend/web/src/components/cocktails/CardCocktail.tsx
  packages/frontend/web/src/components/favorite/Stars.tsx
  packages/frontend/web/src/components/favorite/Title.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/src/pages/Cocktails.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/pages/Favorites.tsx
  packages/frontend/web/src/pages/Virgin.tsx
  packages/frontend/web/src/router.tsx
Labels: Sylvain !

#92 feature : deployment-fix-staging
  deployment/docker-compose.staging.yml
Labels: Sylvain !

#91 done animation home page
  packages/frontend/web/src/components/home/CocktailsPart.tsx
  packages/frontend/web/src/components/home/CommunityPart.tsx
  packages/frontend/web/src/components/home/FavoritesPart.tsx
  packages/frontend/web/src/components/home/ProfilePart.tsx
  packages/frontend/web/src/components/home/ShakeItPart.tsx
  packages/frontend/web/src/components/home/VirginPart.tsx
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !

#94 unique name fix
  packages/backend/api/src/middlewares/multer-config.ts
Labels: Sylvain !, Changes done

#64 Feature/no alcohol shaker
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/ingredient.ts
  packages/backend/api/src/middlewares/validate-cocktail-add.ts
  packages/backend/forge/src/database-data.ts
  packages/backend/migrations/src/migrations/20240127200850-type-ingredient.ts
  packages/backend/migrations/src/migrations/20240212100005-total-kcal-fix.ts
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/FormPart.tsx
  packages/frontend/web/src/components/form-cocktail/GetSquares.tsx
  packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/web/src/components/form-cocktail/MainForm.tsx
  packages/frontend/web/src/components/form-cocktail/ModalSearch.tsx
  packages/frontend/web/src/components/form-cocktail/NamePart.tsx
  packages/frontend/web/src/components/form-cocktail/SoftDrinks.tsx
  packages/frontend/web/src/components/form-cocktail/Syrup.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/tailwind.config.js
  packages/types/src/cocktail-form.ts
  packages/types/src/database.ts
Labels: Sylvain !

#98 fixing file size limit 4 da upload
  packages/backend/api/src/cocktail.ts
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
Labels: Sylvain !

#99 little fix
  packages/backend/api/src/user.ts
  packages/backend/forge/src/database-data.ts
  packages/frontend/web/src/components/CardImage.tsx
  packages/frontend/web/src/components/Layout/LayoutLoggedOut.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
  packages/frontend/web/src/components/cocktails/CardCocktail.tsx
  packages/frontend/web/src/components/profile-page/Card.tsx
  packages/frontend/web/src/pages/Cocktails.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/pages/Favorites.tsx
  packages/frontend/web/src/router.tsx
  packages/types/src/profile.ts
Labels: Sylvain !

#101 come eat
  deployment/docker-compose.dev.yml
  deployment/docker-compose.prod.yml
  deployment/nginx.dev.conf
  deployment/nginx.prod.conf
Labels: Sylvain !

#102 Feature/new pretty favorite bg
  packages/frontend/web/public/favorite-bg.gif
  packages/frontend/web/public/favorites-bg.webp
  packages/frontend/web/src/pages/Favorites.tsx
Labels: Sylvain !

#103 Feature/arrowmodal
  packages/frontend/web/public/scroll-arrow.svg
  packages/frontend/web/src/pages/LegalModal.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !, Conflicts resolved

#107 adding a slash
  packages/frontend/web/src/pages/Login.tsx
  packages/frontend/web/src/pages/Register.tsx
Labels: Sylvain !

#109 trytryttrytrytrytrytry
  packages/frontend/web/src/pages/Home.tsx
Labels: Sylvain !

#104 Feature/transition page
  bun.lockb
  packages/frontend/web/package.json
  packages/frontend/web/public/bg-profile-page.jpg
  packages/frontend/web/public/bg-profile-page.png
  packages/frontend/web/public/feeding-bottle-background.svg
  packages/frontend/web/public/feeding-bottle-cocktails-2.svg
  packages/frontend/web/public/green-dot.png
  packages/frontend/web/public/header-profile.png
  packages/frontend/web/public/profile-page/bg-profil-page.webp
  packages/frontend/web/public/profile-page/header-profile.png
  packages/frontend/web/public/question-mark.png
  packages/frontend/web/public/shake.mp3
  packages/frontend/web/public/shaker.png
  packages/frontend/web/src/components/Navbar.tsx
  packages/frontend/web/src/components/Shaker.tsx
  packages/frontend/web/src/components/VirginCocktailCard.tsx
  packages/frontend/web/src/components/cocktail-detail/VirginCocktailCard.tsx
  packages/frontend/web/src/components/cocktails/CardCocktail.tsx
  packages/frontend/web/src/components/favorite/Title.tsx
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/FormPart.tsx
  packages/frontend/web/src/components/form-cocktail/GetSquares.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/web/src/components/form-cocktail/MainForm.tsx
  packages/frontend/web/src/components/form-cocktail/ModalSearch.tsx
  packages/frontend/web/src/components/form-cocktail/NamePart.tsx
  packages/frontend/web/src/components/form-cocktail/SoftDrinks.tsx
  packages/frontend/web/src/components/form-cocktail/Syrup.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/components/icons/ShakerIcon.tsx
  packages/frontend/web/src/components/profile-page/CommentsSection.tsx
  packages/frontend/web/src/components/profile-page/Header.tsx
  packages/frontend/web/src/components/profile-page/PublicHeader.tsx
  packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/src/pages/Community.tsx
  packages/frontend/web/src/pages/Favorites.tsx
  packages/frontend/web/src/pages/Loading.tsx
  packages/frontend/web/src/pages/Login.tsx
  packages/frontend/web/src/pages/ProfilePage.tsx
  packages/frontend/web/src/pages/PublicProfilePage.tsx
  packages/frontend/web/src/pages/Virgin.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/frontend/web/tsconfig.json
  packages/frontend/web/use-sound.d.ts
Labels: Sylvain !

#110 Feature/fixature
  packages/backend/api/src/cocktail.ts
  packages/backend/forge/src/database-data.ts
  packages/frontend/web/src/components/cocktail-detail/SimilarCocktail.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
Labels: Sylvain !

#111 feature/fix-url-uploads
  packages/frontend/web/src/components/CardImage.tsx
Labels: Sylvain !

#108 Release/v0.2.0
  deployment/docker-compose.dev.yml
  deployment/docker-compose.prod.yml
  deployment/nginx.dev.conf
  deployment/nginx.prod.conf
  packages/backend/api/src/auth.ts
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/ingredient.ts
  packages/backend/api/src/middlewares/validate-cocktail-add.ts
  packages/backend/api/src/user.ts
  packages/backend/forge/src/database-data.ts
  packages/backend/migrations/src/migrations/20240127200850-type-ingredient.ts
  packages/backend/migrations/src/migrations/20240212100005-total-kcal-fix.ts
  packages/frontend/web/public/favorite-bg.gif
  packages/frontend/web/public/favorites-bg.webp
  packages/frontend/web/public/scroll-arrow.svg
  packages/frontend/web/src/components/CardImage.tsx
  packages/frontend/web/src/components/CheckBirthdate.tsx
  packages/frontend/web/src/components/CheckBirthdateAnimations.tsx
  packages/frontend/web/src/components/GreetsLogin.tsx
  packages/frontend/web/src/components/Layout/Layout.tsx
  packages/frontend/web/src/components/Layout/LayoutLoggedOut.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
  packages/frontend/web/src/components/cocktails/CardCocktail.tsx
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/FormPart.tsx
  packages/frontend/web/src/components/form-cocktail/GetSquares.tsx
  packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/web/src/components/form-cocktail/MainForm.tsx
  packages/frontend/web/src/components/form-cocktail/ModalSearch.tsx
  packages/frontend/web/src/components/form-cocktail/NamePart.tsx
  packages/frontend/web/src/components/form-cocktail/SoftDrinks.tsx
  packages/frontend/web/src/components/form-cocktail/Syrup.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/components/profile-page/Card.tsx
  packages/frontend/web/src/contexts/AgeContext.tsx
  packages/frontend/web/src/contexts/AnimationsContext.tsx
  packages/frontend/web/src/contexts/AuthContext.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/main.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/src/pages/Cocktails.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/pages/Favorites.tsx
  packages/frontend/web/src/pages/LegalModal.tsx
  packages/frontend/web/src/pages/Login.tsx
  packages/frontend/web/src/pages/Register.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/types/src/cocktail-form.ts
  packages/types/src/database.ts
  packages/types/src/profile.ts
Labels: Sylvain !

#114 Release/v0.3.0
  bun.lockb
  packages/backend/api/src/cocktail.ts
  packages/backend/forge/src/database-data.ts
  packages/frontend/web/package.json
  packages/frontend/web/public/bg-profile-page.jpg
  packages/frontend/web/public/bg-profile-page.png
  packages/frontend/web/public/feeding-bottle-background.svg
  packages/frontend/web/public/feeding-bottle-cocktails-2.svg
  packages/frontend/web/public/green-dot.png
  packages/frontend/web/public/header-profile.png
  packages/frontend/web/public/profile-page/bg-profil-page.webp
  packages/frontend/web/public/profile-page/header-profile.png
  packages/frontend/web/public/question-mark.png
  packages/frontend/web/public/shake.mp3
  packages/frontend/web/public/shaker.png
  packages/frontend/web/src/components/Navbar.tsx
  packages/frontend/web/src/components/Shaker.tsx
  packages/frontend/web/src/components/VirginCocktailCard.tsx
  packages/frontend/web/src/components/cocktail-detail/SimilarCocktail.tsx
  packages/frontend/web/src/components/cocktail-detail/VirginCocktailCard.tsx
  packages/frontend/web/src/components/cocktails/CardCocktail.tsx
  packages/frontend/web/src/components/favorite/Title.tsx
  packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
  packages/frontend/web/src/components/form-cocktail/FormPart.tsx
  packages/frontend/web/src/components/form-cocktail/GetSquares.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
  packages/frontend/web/src/components/form-cocktail/MainForm.tsx
  packages/frontend/web/src/components/form-cocktail/ModalSearch.tsx
  packages/frontend/web/src/components/form-cocktail/NamePart.tsx
  packages/frontend/web/src/components/form-cocktail/SoftDrinks.tsx
  packages/frontend/web/src/components/form-cocktail/Syrup.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/components/icons/ShakerIcon.tsx
  packages/frontend/web/src/components/profile-page/CommentsSection.tsx
  packages/frontend/web/src/components/profile-page/Header.tsx
  packages/frontend/web/src/components/profile-page/PublicHeader.tsx
  packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/pages/Community.tsx
  packages/frontend/web/src/pages/Favorites.tsx
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/src/pages/Loading.tsx
  packages/frontend/web/src/pages/Login.tsx
  packages/frontend/web/src/pages/ProfilePage.tsx
  packages/frontend/web/src/pages/PublicProfilePage.tsx
  packages/frontend/web/src/pages/Register.tsx
  packages/frontend/web/src/pages/Virgin.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/frontend/web/tsconfig.json
  packages/frontend/web/use-sound.d.ts
Labels: Sylvain !

#115 oui
  packages/frontend/web/src/components/form-cocktail/FormPart.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !

#116 non
  deployment/docker-compose.staging.yml
Labels: Sylvain !

#119 Feature/staging forge
  packages/backend/migrations/src/migrations/20240228153506-insert-glass.ts
  packages/backend/migrations/src/migrations/20240228153507-insert-user.ts
  packages/backend/migrations/src/migrations/20240228153508-insert-ingredient.ts
  packages/backend/migrations/src/migrations/20240228153509-insert-cocktail.ts
  packages/backend/migrations/src/migrations/20240228153510-insert-favorite.ts
  packages/backend/migrations/src/migrations/20240228153511-insert-topping.ts
  packages/backend/migrations/src/migrations/20240228153512-insert-tool.ts
  packages/backend/migrations/src/migrations/20240228153513-insert-action.ts
  packages/backend/migrations/src/migrations/20240228153514-insert-action-ingredient.ts
  packages/backend/migrations/src/migrations/20240228153515-insert-cocktail-topping.ts
  packages/backend/migrations/src/migrations/20240228153516-insert-recipe.ts
Labels: Sylvain !

#121 Feature : staging-tool
  packages/backend/migrations/src/migrations/20240228153512-insert-tool.ts
Labels: Sylvain !

#122 feature : tool-fix
  packages/backend/migrations/src/migrations/20240228153512-insert-tool.ts
  packages/backend/migrations/src/migrations/20240229111551-insert-tool-update.ts
Labels: Sylvain !

#120 Release/v0.4.0
  deployment/docker-compose.staging.yml
  packages/backend/migrations/src/migrations/20240228153506-insert-glass.ts
  packages/backend/migrations/src/migrations/20240228153507-insert-user.ts
  packages/backend/migrations/src/migrations/20240228153508-insert-ingredient.ts
  packages/backend/migrations/src/migrations/20240228153509-insert-cocktail.ts
  packages/backend/migrations/src/migrations/20240228153510-insert-favorite.ts
  packages/backend/migrations/src/migrations/20240228153511-insert-topping.ts
  packages/backend/migrations/src/migrations/20240228153512-insert-tool.ts
  packages/backend/migrations/src/migrations/20240228153513-insert-action.ts
  packages/backend/migrations/src/migrations/20240228153514-insert-action-ingredient.ts
  packages/backend/migrations/src/migrations/20240228153515-insert-cocktail-topping.ts
  packages/backend/migrations/src/migrations/20240228153516-insert-recipe.ts
  packages/backend/migrations/src/migrations/20240229111551-insert-tool-update.ts
  packages/frontend/web/src/components/form-cocktail/FormPart.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain
