Repository WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a, pull requests merged in 2024-01, with the labels that each got.

#25 Feature/topping suggestion
  packages/backend/api/src/ingredient.ts
  packages/backend/api/src/router.ts
  packages/backend/api/src/services/topping-service.ts
  packages/backend/api/src/topping.ts
  packages/backend/forge/src/database-data.ts
  packages/backend/migrations/src/migrations/20231215130413-edit-topping.ts
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/types/src/cocktail-form.ts
  packages/types/src/database.ts
Labels: Sylvain !

#31 Feature/navbar
  packages/frontend/web/src/Layout.tsx
  packages/frontend/web/src/components/Navbar.tsx
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
Labels: Sylvain !

#27 Feature/other ingredient
  packages/backend/api/src/ingredient.ts
  packages/frontend/web/src/components/Navbar.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
  packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
  packages/frontend/web/src/components/form-cocktail/ModalSearch.tsx
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
  packages/frontend/web/src/pages/AddCocktail.tsx
  packages/types/src/cocktail-form.ts
Labels: Sylvain !

#35 hotfix: auth-backend-cookie-id
  packages/backend/api/src/auth.ts
Labels: Sylvain !, RUBEN'S LABEL

#37 hotfix : topping-suggestion
  packages/backend/api/src/services/topping-service.ts
  packages/backend/api/src/topping.ts
  packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
Labels: Sylvain !

#36 Feature/upload cocktail picture
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/index.ts
  packages/backend/api/src/middlewares/multer-config.ts
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/types/src/profile.ts
Labels: Sylvain !, Changes done, RUBEN'S LABEL

#29 Feature/show cocktail
  packages/backend/api/src/cocktail.ts
  packages/backend/api/src/comment.ts
  packages/backend/api/src/filter.ts
  packages/backend/api/src/router.ts
  packages/frontend/web/public/bg-cocktails.png
  packages/frontend/web/public/blue-dot.png
  packages/frontend/web/public/cocktail-img.png
  packages/frontend/web/public/shaker.svg
  packages/frontend/web/src/components/cocktail-detail/AddComment.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailCard.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
  packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
  packages/frontend/web/src/components/cocktail-detail/Comment.tsx
  packages/frontend/web/src/components/cocktails/CardCocktail.tsx
  packages/frontend/web/src/components/cocktails/CardTitle.tsx
  packages/frontend/web/src/components/cocktails/FilterBar.tsx
  packages/frontend/web/src/components/cocktails/SearchBar.tsx
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/Cocktails.tsx
  packages/frontend/web/src/pages/CocktailsDetails.tsx
  packages/frontend/web/src/pages/Home.tsx
  packages/frontend/web/src/router.tsx
Labels: Sylvain !, Changes done

#18 Feature/auth frontend
  bun.lockb
  packages/backend/api/src/auth.ts
  packages/backend/api/src/middlewares/validate-login.ts
  packages/backend/api/src/middlewares/validate-register.ts
  packages/frontend/web/public/alcohol-free-cocktails.webp
  packages/frontend/web/public/enter.svg
  packages/frontend/web/public/feeding-bottle-background.svg
  packages/frontend/web/public/mom-said-no.png
  packages/frontend/web/public/ouch.svg
  packages/frontend/web/public/wow.svg
  packages/frontend/web/public/yes-you-can.svg
  packages/frontend/web/src/Layout.tsx
  packages/frontend/web/src/components/CheckBirthdate.tsx
  packages/frontend/web/src/components/CheckBirthdateAnimations.tsx
  packages/frontend/web/src/components/GreetsLogin.tsx
  packages/frontend/web/src/components/Layout/Layout.tsx
  packages/frontend/web/src/components/Layout/LayoutLoggedOut.tsx
  packages/frontend/web/src/contexts/AnimationsContext.tsx
  packages/frontend/web/src/contexts/AuthContext.tsx
  packages/frontend/web/src/contexts/BirthContext.tsx
  packages/frontend/web/src/main.tsx
  packages/frontend/web/src/pages/LegalModal.tsx
  packages/frontend/web/src/pages/Login.tsx
  packages/frontend/web/src/pages/NoKidsAllowed.tsx
  packages/frontend/web/src/pages/Register.tsx
  packages/frontend/web/src/router.tsx
  packages/frontend/web/tailwind.config.js
  packages/frontend/web/tsconfig.json
  packages/types/src/auth-register.ts
  packages/types/src/database.ts
  tsconfig.json
Labels: Sylvain !, Changes done

#63 fix: style card community page
  packages/frontend/web/public/purple-dot.png
  packages/frontend/web/src/globals.css
  packages/frontend/web/src/pages/Community.tsx
Labels: Sylvain !

#65 adding some data & pictures
  packages/backend/forge/src/database-data.ts
  packages/frontend/web/public/tools/bar-spoon.png
  packages/frontend/web/public/tools/blender.png
  packages/frontend/web/public/tools/citrus-juicer.png
  packages/frontend/web/public/tools/ice-pick.png
  packages/frontend/web/public/tools/jigger.png
  packages/frontend/web/public/tools/knife.png
  packages/frontend/web/public/tools/muddler.png
  packages/frontend/web/public/tools/shaker.png
  packages/frontend/web/public/tools/spoon.png
  packages/frontend/web/public/tools/stirring-glass.png
  packages/frontend/web/public/tools/strainer.png
Labels: Sylvain !
